---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: session-db-h2
spec:
  template:
    metadata:
      labels:
        app: session-db-h2
    spec:
      containers:
      - name: session-db-h2
        image: docker-registry.default.svc:5000/chipster-dev/h2
        ports:                
        - name: h2-server
          containerPort: 1521
        - name: h2-console
          containerPort: 8081
        volumeMounts:
        - mountPath: /opt/h2-data
          name: h2-data
      volumes:
      - name: h2-data
        persistentVolumeClaim:
          claimName: session-db-h2-data
  replicas: 1
          