apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-api
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${{NAME}}
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: api
    selector:
      app: ${{NAME}}
    sessionAffinity: None
    type: ClusterIP
    
parameters:
- name: NAME
- name: PROJECT
- name: DOMAIN
