apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-api
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${{NAME}}
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: api
    selector:
      app: ${{NAME}}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${NAME}-${PROJECT}.${DOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${{NAME}}
      weight: 100
    wildcardPolicy: None
    
parameters:
- name: NAME
- name: PROJECT
- name: DOMAIN
