---
apiVersion: v1
kind: Route
metadata:
  name: grafana
  annotations: 
    haproxy.router.openshift.io/ip_whitelist: "{{&admin-ip-whitelist}}"
spec:
  to:
    kind: Service
    name: grafana
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge