---
apiVersion: v1
kind: Route
metadata:
  name: web-server
spec:
  host: {{project}}.{{app-domain}}
  to:
    kind: Service
    name: web-server
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge